import {useState} from 'react';
import type {Evidence,Route} from './contextTypes';
const stamp=(s:string|null|undefined)=>s?new Date(s).toLocaleString('ru-RU',{timeZone:'Europe/Moscow'})+' МСК':'—';
const names:Record<string,string>={ok:'Получены',stale:'Устарели / нет обновления',unavailable:'Недоступны',not_configured:'Не подключён',disabled:'Отключены'};
const n=(v:number)=>v.toLocaleString('ru-RU',{maximumFractionDigits:2});
type Result={segment_before_seconds:number;segment_after_seconds:number;delta_seconds:number;headway_before_minutes:number;headway_after_minutes:number;wait_before_minutes:number;wait_after_minutes:number;effective_reserve:number;formulas:string[];assumptions:string[];inputs:Record<string,number>};
const initial={cycle_minutes:60,fleet:10,reserve:1,segment_km:2,baseline_speed_kmh:30,scenario_speed_kmh:15,added_dwell_seconds:30,horizon_minutes:15,dispatch_minutes:5};
const fields:Record<keyof typeof initial,string>={cycle_minutes:'Оборот, мин',fleet:'ТС на линии',reserve:'Резерв, ТС',segment_km:'Длина участка, км',baseline_speed_kmh:'Исходная скорость, км/ч',scenario_speed_kmh:'Сценарная скорость, км/ч',added_dwell_seconds:'Доп. простой, с',horizon_minutes:'Горизонт, мин (10–15)',dispatch_minutes:'Выпуск резерва через, мин'};
export default function ContextPanel({evidence,error,routes,token,onImport,activeTab}:{activeTab?:'evidence'|'scenario'|'imports';evidence:Evidence|null;error:string;routes:Route[];token:string;onImport:()=>void}){
 const [internalTab,setTab]=useState('evidence'),[inputs,setInputs]=useState(initial),[result,setResult]=useState<Result|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const tab=activeTab||internalTab;
 const post=async(url:string,body:unknown)=>{const r=await fetch('/api'+url,{method:'POST',headers:{'Content-Type':'application/json',...(token?{'X-Ingest-Token':token}:{})},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));return data;};
 const importFile=async(file:File|undefined,url:string)=>{if(!file)return;setMessage('');setBusy(true);try{if(file.size>5_000_000)throw Error('Файл больше 5 МБ');const data=JSON.parse(await file.text());const response=await post(url,data);setMessage(`Принято записей: ${response.accepted}. Источник указан автором файла и не подтверждается автоматически.`);onImport();}catch(e){setMessage(String(e));}finally{setBusy(false);}};
 const exportEvidence=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(evidence,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='external-evidence.json';a.click();URL.revokeObjectURL(url);};
 const weather=evidence?.weather,events=evidence?.road_events,w=weather?.data;
 return <section className="context-panel">{!activeTab&&<div className="context-tabs" role="tablist" aria-label="Аналитика и внешние данные">{[['evidence','Факторы и источники'],['scenario','What-if · сценарий'],['imports','Данные и маршруты']].map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} className={tab===id?'chosen':''} onClick={()=>{setTab(id);setMessage('');}}>{label}</button>)}<span>Проверяемые данные · явные допущения</span></div>}
 {error&&<p className="notice" role="alert">{error} Показано последнее полученное состояние; его актуальность не подтверждена.</p>}
 {tab==='evidence'&&<><div className="context-intro"><div><h2>Что происходит рядом</h2><p>Радиус 1 км от выбранной зоны; без выбора — центр Москвы. Погода представляет одну модельную ячейку.</p></div><button disabled={!evidence} onClick={exportEvidence}>Скачать доказательства · JSON</button></div>{evidence?.replay_notice&&<p className="notice">{evidence.replay_notice}</p>}<div className="evidence-grid">
 <article className="evidence-card"><div className="evidence-heading"><h3>Погода</h3><span className={'source-badge '+weather?.status}>{names[weather?.status||'unavailable']}</span></div>{w?<><div className="weather-values"><strong>{n(w.values.temperature_2m)}°<small>температура</small></strong><strong>{n(w.values.precipitation)}<small>мм осадков / интервал</small></strong><strong>{n(w.values.wind_speed_10m)}<small>м/с ветер</small></strong></div><p>{w.scope}</p><p>Модельное время: {stamp(w.observed_at)}<br/>Получено: {stamp(w.fetched_at)}</p><a href={w.source_url} target="_blank" rel="noreferrer">{w.source} · методика и единицы ↗</a></>:<p>Ожидается ответ Open-Meteo. При ошибке вымышленные значения не подставляются.</p>}{weather?.error&&<p className="warning-text">{weather.error}</p>}</article>
 <article className="evidence-card"><div className="evidence-heading"><h3>ДТП, работы, перекрытия</h3><span className={'source-badge '+events?.status}>{names[events?.status||'unavailable']}</span></div><p><b>{events?.source_name||'Источник ЦОДД не настроен'}</b></p>{events?.metadata&&<p>{events.metadata.transport==='manual_import'?'Пользовательский импорт':'Настроенный адаптер'} · дата источника {stamp(events.generated_at)}</p>}<div className="events-list">{events?.events.map(e=><a key={e.id} href={e.source_url} target="_blank" rel="noreferrer"><b>{e.kind==='accident'?'ДТП':e.kind==='roadworks'?'Работы':'Перекрытие'} · {n(e.distance_m)} м</b><span>{e.title} ↗</span><small>Действует до {stamp(e.ends_at)}</small></a>)}</div>{!events?.events.length&&<p>Подходящих записей нет. Это не означает, что дороги свободны.</p>}<p>{events?.coverage}</p>{events?.error&&<p className="warning-text">{events.error}</p>}<a href="https://transport.mos.ru/mostrans/closures" target="_blank" rel="noreferrer">Официальная карта ЦОДД ↗</a></article>
 <article className="evidence-card"><div className="evidence-heading"><h3>Как это влияет на прогноз</h3><span className="source-badge">Контекст</span></div><p>{evidence?.explanation||'Внешние данные не изменяют ML-прогноз.'}</p><p>В what-if можно задать скорость и простой, затем проверить расчёт по формулам. Коэффициенты «дождь → задержка» не выдумываются.</p><details><summary>Формулы и фильтры данных</summary>{Object.entries(evidence?.formulas||{}).map(([k,v])=><code key={k}>{v}</code>)}<p>Порог свежести — эксплуатационная настройка, а не точность источника. Географическая близость — не доказанная причина.</p></details><details><summary>Формула существующего индекса риска</summary><code>R = 50·clip(D/600) + 20·clip(C/300) + 15·clip(S/20) + 15·clip(A/5)</code><p>clip ограничивает значение до [0,1]. D — задержка выбранного режима, C — текущая задержка (секунды), S — падение скорости (км/ч), A — число ТС с задержкой более 120 с. Веса — правила проекта; R не является вероятностью.</p></details>{events?.metadata&&<details><summary>Отпечаток исходной выгрузки</summary><code>{events.metadata.sha256}</code><p>SHA-256 подтверждает неизменность загруженного содержимого, но не достоверность автора.</p></details>}</article>
 </div></>}
 {tab==='scenario'&&<div className="scenario-grid"><div><h2>Проверить действие диспетчера</h2><p className="hint">Начальные числа — учебные допущения, не данные Москвы. Задайте параметры вашего маршрута.</p><form onSubmit={e=>{e.preventDefault();setBusy(true);setMessage('');void post('/analysis/what-if',inputs).then(setResult).catch(e=>setMessage(String(e))).finally(()=>setBusy(false));}}><div className="scenario-inputs">{(Object.keys(inputs) as (keyof typeof inputs)[]).map(k=><label key={k}>{fields[k]}<input required type="number" step={['fleet','reserve','horizon_minutes'].includes(k)?1:'any'} min={['baseline_speed_kmh','scenario_speed_kmh'].includes(k)?0.01:k==='horizon_minutes'?10:['fleet','cycle_minutes'].includes(k)?1:0} max={k==='horizon_minutes'?15:undefined} value={inputs[k]} onChange={e=>{setInputs({...inputs,[k]:Number(e.target.value)});setResult(null);}}/></label>)}</div><button className="primary-button" disabled={busy}>Рассчитать сценарий</button></form></div><div>{result?<><h2>Результат по введённым параметрам</h2><div className="scenario-results"><div><small>Изменение проезда</small><strong>{result.delta_seconds>=0?'+':''}{n(result.delta_seconds)} с</strong><span>{n(result.segment_before_seconds)} → {n(result.segment_after_seconds)} с</span></div><div><small>Интервал</small><strong>{n(result.headway_after_minutes)} мин</strong><span>Исходный: {n(result.headway_before_minutes)} мин</span></div><div><small>Среднее ожидание</small><strong>{n(result.wait_after_minutes)} мин</strong><span>Исходное: {n(result.wait_before_minutes)} мин</span></div></div><p>Учтённый резерв: {result.effective_reserve} ТС. Выпуск позже горизонта не учитывается.</p><div className="formula-box">{result.formulas.map(f=><code key={f}>{f}</code>)}</div><ul className="assumptions">{result.assumptions.map(a=><li key={a}>{a}</li>)}</ul></>:<div className="scenario-placeholder"><strong>От допущений к проверяемому результату</strong><p>t = 3600·L/v · H = C/N · E[W] = H/2</p><span>Расчёт появится после нажатия кнопки. Это сценарная оценка, а не прогноз модели.</span></div>}</div></div>}
 {tab==='imports'&&<div className="imports-grid"><article className="evidence-card"><h2>Официальные дорожные события</h2><p>Загрузите JSON по EventFeed 1.0: source_name, generated_at, events. Каждая запись содержит id, kind, title, lat, lon, starts_at, ends_at, published_at, source_url. Все даты — с часовым поясом.</p><label className="file-label">Импорт событий<input disabled={busy} aria-label="Импорт событий JSON" type="file" accept=".json,application/json" onChange={e=>{void importFile(e.target.files?.[0],'/external/events/import');e.target.value='';}}/></label><p>Адрес настоящего API и токен настраиваются на сервере: CODD_FEED_URL, CODD_API_TOKEN. Адаптер ожидает этот же контракт. Автоматический доступ к ЦОДД пока не подтверждён.</p></article><article className="evidence-card"><h2>Геометрия маршрутов · {routes.length}</h2><p>Формат: routes: [id, name, source_url, coordinates]. Координаты в порядке [долгота, широта]. Линии появятся на схеме и в Яндекс Картах.</p><label className="file-label">Импорт маршрутов<input disabled={busy} aria-label="Импорт маршрутов JSON" type="file" accept=".json,application/json" onChange={e=>{void importFile(e.target.files?.[0],'/network/routes/import');e.target.value='';}}/></label>{routes.slice(0,10).map(r=><p key={r.id}><a href={r.source_url} target="_blank" rel="noreferrer">{r.name} ↗</a> · {r.coordinates.length} точек</p>)}<p>Базовая геометрическая привязка доступна через API /network/map-match. Пересекающиеся маршруты помечаются как неоднозначные; маршрут ТС не выдумывается.</p></article><article className="evidence-card"><h2>Подключение Яндекс Карт</h2><p>Добавьте VITE_YANDEX_MAPS_API_KEY в корневой .env и перезапустите интерфейс. Ограничьте браузерный ключ доменами локального тестирования.</p><p>Переключатель карты расположен в правом нижнем углу схемы. Слои пробок и событий доступны по соответствующему платному тарифу; они отключены в историческом replay.</p><a href="https://yandex.ru/maps-api/docs/js-api/examples/cases/traffic.html" target="_blank" rel="noreferrer">Официальная документация ↗</a><p>Доступы хранятся локально. Для защищённого импорта введите INGEST_TOKEN в панели управления.</p></article></div>}
 {message&&<p className="notice" role="status">{message}</p>}</section>;
}
