import {useState} from 'react';
import {ArrowRight,BookOpen,Check,ChevronRight,Clock3,Info,Layers3,MapPin,Play,Search,ShieldCheck,SlidersHorizontal,TriangleAlert} from 'lucide-react';
export type Destination='monitor'|'evidence'|'scenario'|'imports';
const lessons=[
 {title:'Начните с мониторинга',time:'Шаг 1 из 4',Icon:Play,lead:'Посмотрите движение на исторических данных.',steps:['Откройте «Мониторинг» в меню слева.','Нажмите жёлтую кнопку ▶ под картой. При первом запуске дождитесь подготовки истории.','Выберите скорость ×1, ×10 или ×50. Кнопка паузы остановит воспроизведение.'],note:'REPLAY — записи прошлого периода. Время вверху экрана относится к источнику данных, а не к текущим часам.',target:'monitor' as Destination,action:'Открыть мониторинг'},
 {title:'Найдите проблемную зону',time:'Шаг 2 из 4',Icon:MapPin,lead:'Сравните текущее положение и ожидаемые задержки.',steps:['Выберите «Сейчас» или «Прогноз 10–15 мин» над картой.','Посмотрите список «Требуют внимания». Нажмите на зону — под картой откроются её показатели и рекомендации.','В фильтрах можно ограничить уровень риска, скрыть транспорт или индекс риска. Для поиска используйте номер ТС, адрес либо ID остановочного события.'],note:'Число риска от 0 до 100 — индекс по правилам проекта. Это не процент вероятности. Прочерк означает отсутствие известного значения.',target:'monitor' as Destination,action:'Посмотреть зоны'},
 {title:'Проверьте факты и источники',time:'Шаг 3 из 4',Icon:Layers3,lead:'Узнайте, откуда взялись значения и насколько они актуальны.',steps:['Откройте «Факторы». Там показаны погода и доступные дорожные события.','Сверьте дату источника, дату получения и статус свежести. Для событий проверьте ссылку на первоисточник.','Откройте формулы или скачайте JSON со сведениями об источниках, если нужно проверить расчёт.'],note:'Сегодняшняя погода не объясняет январскую поездку. Внешние факторы показываются отдельно и не меняют прогноз ML. Пустой список ДТП не означает, что происшествий нет.',target:'evidence' as Destination,action:'Проверить источники'},
 {title:'Оцените своё решение',time:'Шаг 4 из 4',Icon:SlidersHorizontal,lead:'Сравните исходный режим движения и выбранный сценарий.',steps:['Откройте «Сценарии» и введите параметры маршрута: оборот, число ТС, длину участка и скорости.','При необходимости укажите резерв, время его выпуска и дополнительный простой.','Нажмите «Рассчитать сценарий». Сравните время проезда, интервал и среднее ожидание; прочитайте формулы и допущения.'],note:'Начальные числа в форме — учебный пример. Расчёт не запускает автобусы и не меняет расписание: окончательное решение принимает диспетчер.',target:'scenario' as Destination,action:'Попробовать сценарий'},
];
const faq=[
 ['Почему вместо улиц видна сетка?','Это координатная схема без картографической подложки. Реальные загруженные точки остаются видимыми. Для Яндекс Карт нужен настроенный ключ; инструкция находится в разделе «Данные».'],
 ['Почему на карте ничего нет?','Проверьте, загружен ли датасет и запущена ли история движения. Дождитесь подготовки. Затем откройте фильтры, выберите «Все зоны» и включите «Транспорт». В LIVE нужен входящий поток телеметрии.'],
 ['Чем LIVE отличается от REPLAY?','LIVE принимает поступающие сообщения. REPLAY воспроизводит сохранённую историю. Метка LIVE сама по себе не подтверждает, что данные сегодняшние: всегда смотрите время источника и состояние потока.'],
 ['Что означают «Сейчас», «Прогноз» и «Факт»?','«Сейчас» — известное отклонение по поступившим данным. «Прогноз» — оценка модели на горизонт 10–15 минут. «Факт» появляется после наблюдения целевого события. До этого ошибка прогноза может быть неизвестна.'],
 ['Почему значения не обновляются?','При паузе истории это ожидаемо. Если показана ошибка подключения, интерфейс сохраняет последние полученные значения; их актуальность не подтверждена. Проверьте состояние системы, возобновите историю либо сообщите администратору.'],
 ['Что делать со статусом «Не подключён» у дорожных событий?','Источник ещё не настроен. Это не нулевое число происшествий. Администратор может подключить согласованный источник или импортировать проверенную выгрузку в разделе «Данные».'],
 ['Почему разные цвета и цифры не совпадают с процентом?','Цвет соответствует диапазону расчётного индекса: менее 40 — зелёный, от 40 до 60 — жёлтый, от 60 — красный. В список внимания попадают зоны от 20. Число 60 не означает вероятность 60%.'],
 ['Перемотка не происходит сразу — это ошибка?','Для выбранного времени система заново обрабатывает предшествующие сообщения, сохраняя порядок событий. Подготовка может занимать несколько минут. После завершения перемотки воспроизведение остаётся на паузе.'],
];
export default function Help({onNavigate}:{onNavigate:(target:Destination)=>void}){
 const [step,setStep]=useState(0),[done,setDone]=useState<number[]>([]),[query,setQuery]=useState('');
 const lesson=lessons[step],LessonIcon=lesson.Icon;
 const filtered=faq.filter(([q,a])=>(q+' '+a).toLocaleLowerCase('ru').includes(query.trim().toLocaleLowerCase('ru')));
 const complete=()=>{setDone(prev=>prev.includes(step)?prev:[...prev,step]);if(step<3)setStep(step+1);};
 return <div className="learning-page">
  <section className="learning-welcome"><div className="learning-mark"><BookOpen size={28}/></div><div><span className="learning-kicker">БЫСТРЫЙ СТАРТ</span><h2>Разберитесь в рабочем месте за четыре шага</h2><p>От первого запуска до решения по маршруту. Можно изучать в своём темпе и возвращаться к инструкции в любой момент.</p></div><div className="learning-progress"><strong>{done.length}<span> / 4</span></strong><span>шагов отмечено</span><progress aria-label="Прогресс обучения" value={done.length} max={4}/></div></section>
  <div className="learning-layout"><nav className="lesson-menu" aria-label="Шаги обучения">{lessons.map((item,i)=><button key={item.title} onClick={()=>setStep(i)} aria-current={step===i?'step':undefined} className={step===i?'is-current':''}><span className={'lesson-number '+(done.includes(i)?'is-done':'')}>{done.includes(i)?<Check size={16}/>:String(i+1).padStart(2,'0')}</span><span>{item.title}<small>{done.includes(i)?'Вы отметили как изученное':'Пошаговая инструкция'}</small></span><ChevronRight size={16}/></button>)}<div className="lesson-tip"><ShieldCheck size={19}/><p>Изучение инструкции не изменяет данные и настройки системы.</p></div></nav>
   <article className="lesson-card" aria-labelledby="lesson-title"><div className="lesson-meta"><span><LessonIcon size={17}/>{lesson.time}</span><span><Clock3 size={14}/>Без спешки</span></div><h2 id="lesson-title">{lesson.title}</h2><p className="lesson-lead">{lesson.lead}</p><ol className="lesson-instructions">{lesson.steps.map((text,i)=><li key={text}><span>{i+1}</span><p>{text}</p></li>)}</ol><div className="lesson-note"><Info size={18}/><p>{lesson.note}</p></div><div className="lesson-actions"><button className="primary-button" onClick={()=>onNavigate(lesson.target)}>{lesson.action}<ArrowRight size={16}/></button><button className="lesson-next" onClick={complete}>{step===3?(done.length===4?'Все шаги отмечены':'Отметить как изученное'):'Понятно, следующий шаг'}<Check size={16}/></button></div>{done.length===4&&<p className="learning-complete" role="status">Все шаги отмечены. Инструкция останется доступной в меню слева.</p>}</article>
  </div>
  <section className="reading-guide"><div><h2>Как читать показатели</h2><p>Три различия, которые помогают не ошибиться в решении.</p></div><div className="reading-grid"><article><span className="reading-label">ВРЕМЯ</span><h3>+3:20 — опоздание</h3><p>Три минуты двадцать секунд. Подпись «раньше» означает опережение. Прочерк — значение неизвестно.</p></article><article><span className="reading-label">РИСК</span><h3>Индекс, а не вероятность</h3><p>Сравнивайте зоны и вклад факторов. Формула доступна в разделе «Факторы».</p></article><article><span className="reading-label">ИСТОЧНИК</span><h3>Дата важнее статуса LIVE</h3><p>Проверяйте время телеметрии. Свежая погода и историческая поездка относятся к разным периодам.</p></article></div></section>
  <section className="learning-faq"><div className="faq-heading"><div><h2>Если что-то непонятно</h2><p>Ответы на частые вопросы о карте, данных и расчётах.</p></div><label className="faq-search"><Search size={17}/><input aria-label="Поиск по справке" placeholder="Например: карта или прогноз" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="faq-list">{filtered.map(([q,a])=><details key={q}><summary>{q}<ChevronRight size={16}/></summary><p>{a}</p></details>)}{!filtered.length&&<p className="faq-empty" role="status">Ничего не найдено. Попробуйте другое слово или очистите поиск.</p>}</div></section>
  <div className="learning-caution"><TriangleAlert size={17}/><p>Рекомендации и сценарии помогают оценить ситуацию. Они не являются автоматическими распоряжениями по движению транспорта.</p></div>
 </div>;
}
